# Generated by Django 3.1.7 on 2021-03-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='left_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='right_number',
            field=models.IntegerField(default=0),
        ),
    ]
